version: "3.9"

services:
  x-crm-api:
    container_name: x-crm-api
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    working_dir: /var/www
    volumes:
      - ./:/var/www # code
    depends_on:
      - x-crm-postgres
    expose:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Develompent
      - ASPNETCORE_URLS=http://+:5000;
      - "TZ=Europe/Moscow"
    command: ["dotnet", "/var/www/x-crm-manage-api.dll"]
    restart: unless-stopped
    
  x-crm-postgres:
    container_name: x-crm-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rtx5070TINNN
      POSTGRES_DB: db
      TZ: Europe/Moscow
    volumes:
      - ../database/postgres:/var/lib/postgresql/data
      - ../database/dumps/:/var/dumps/
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  x-crm-pgadmin:
    container_name: x-crm-pgadmin
    user: "${UID}:${GID}"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminrtx5070TINNN
    volumes:
      - ../database/pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"


networks:
  default:
    name: docker-net
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450